### ISSUE TITLE
euphoria-flink: Allowed lateness

### ISSUE THREAD

**Issue by vanekjar** [seznam/euphoria#61]
In streaming environment it happens elements arrive out-of-order. Our `FlinkExecutor` has a possibility to setup a time period called `allowed lateness` via `setAllowedLateness` method. Allowed lateness specifies by how much time elements can be late before they are dropped.

Currently `allowed lateness` is applied during event time assignment in `ReduceStateByKeyTranslator.EventTimeAssigner`. In case no event time extraction is used (i. e. flow is run using `ingestion` time characteristics) the `allowed lateness` is ignored. It would be better to move `allowed lateness` to `AbstractWindowOperator` and remove it from assigner.

**Comment by je-ik** [comment]
I'm not 100% sure what this implies, so just a remark - `allowed lateness` is a runtime charasteristic, not a business logic attribute, so it should not be visible to application user. It would be great if we could strictly separate application logic (where user can suppose to have _ideal_ stream conditions - i.e. exactly once semantics with no out-of-ordering) and the settings that are needed in order to get as close as possible to this ideal conditions should be kept in the executor settings.

Therefore, one can write a flow and then execute it under different settings of the allowed lateness, which will likely be set by an operations person, rather than the application developer.
