### ISSUE TITLE
FIndbugs plugin is bound to incorrect phase

### ISSUE THREAD

**Issue by je-ik** [seznam/euphoria#85]
Currently the findbugs plugin runs in `compile` phase, which is not correct, because by that time no source files are ready for analysis yet. We should bind probably to `test` phase.

**Comment by xitep** [comment]
Hm, it appears to work correctly for me (using maven 3.5.0). Otherwise, I'd expect `mvn clean compile` to skip detecting problems.

If it's a problem for you, which maven version do you have? How, can I reproduce the problem at your side? Maybe the compile phase is indeed not correct, and we should switch over to `process-classes` can you tried that out for your scenario (https://maven.apache.org/ref/3.5.0/maven-core/lifecycles.html)?

**Comment by je-ik** [comment]
Interesting, now it seems to work for me also. But I have seen this problem on another project. MIght it be the case that the ordering of plugin execution within maven phase is not well defined?

**Comment by xitep** [comment]
digging a bit deeper into maven, i believe it's safer to switch over to the mentioned `process-classes` phase; i'll set up a pr for that.

**Comment by xitep** [comment]
thanks for reporting!
