### ISSUE TITLE
euphoria-flink: disable object-reuse mode

### ISSUE THREAD

**Issue by vanekjar** [seznam/euphoria#98]
> In object-reuse enabled mode, Flink’s runtime minimizes the number of object instantiations. This can improve the performance and can reduce the Java garbage collection pressure.

More about this feature can be found in [Flink documentation](https://ci.apache.org/projects/flink/flink-docs-release-1.2/dev/batch/index.html#object-reuse-enabled).

We tried to make use of this feature in Euphoria executor, but it turned out it may (and it will) cause problems in case of iteration over whole partition while remembering input objects. This is typical behavior for `ReduceByKey` or `ReduceStateByKey` where input objects are stored as a state.

Referring to Flink documentation:
> Input objects received from an Iterable are only valid until the next() method is called. An Iterable or Iterator may serve the same object instance multiple times. It is not safe to remember input objects received from an Iterable, e.g., by putting them in a List or Map. 

Proposed solution is to give up this performance benefit and disable object reuse completely.

**Comment by je-ik** [comment]
Can you please explain a little more in detail the reason why are the elements cached in the state? I would think that because the state by definition has to be serializable, the problem could be solved by cloning the elements into the state (when the state is updated). Would this solve the issue?

**Comment by xitep** [comment]
cloning would surely prevent the troubles, but cloning defeats the purposes of having object-reuse in the first place. from the top of my head, [this one](https://github.com/seznam/euphoria/blob/master/euphoria-flink/src/main/java/cz/seznam/euphoria/flink/batch/BatchStateStorageProvider.java) is seriously affected by object-reuse. i guess, our flink executor implementation is just not ready for supporting object-reuse yet. i agree with taking out the option for the moment.

**Comment by vanekjar** [comment]
I basically agree that if we make sure that objects are cloned at all places where the state is stored we could let the Flink's `object reuse` enabled. But cloning objects will eliminate all the benefits of object reuse anyway. So the question is if it's worth the effort now.

**Comment by je-ik** [comment]
I don't say we should not do it, just trying to clarify the problem for myself. :)

I would think that cloning the state doesn't entirely defeat, because Flink has to do it the same way (or it would run into the same issues as we do). The objects might be reused more often than the state is updated (for example for stateless operators, but this will be most likely true even for stateful operators).

I'm trying to figure out, if there isn't something other fundamentally wrong with our state handling, because as I see the state, it should definitely be considered "persistent and fault tolerant" for all practical executors. This persistence and fault tolerance implies that the contents of the state must be serializable, which removes the described problem (supposing that the serialization would occur with every inserted element, which might not be true).
If the serialization occurs only at a certain time periods (checkpoints), then in the time between the checkpoints, the issue exists. So, do we know how Flink solves this? I can imagine some dirty solutions, but there might be some cleaner way.

**Comment by xitep** [comment]
yes, it's not fully correct what i said. cloning at certain places doesn't fully defeat the purpose. i agree. there still would be (small) benefits. however, for the moment i will take away the possibility to enable object re-use and set up a ticket to enable it as a feature to be supported.
